name: Build Dotnet Project
on:
  push:
    tags:
      - 'v*'   # 例如推送 v1.0.0 时触发

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build WarningUnlock/WarningUnlock.csproj
      - name: Publish
        run: dotnet publish WarningUnlock/WarningUnlock.csproj -c Release -r win-x64 -o ./publish
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: publish/*.exe
          draft: true
          fail_on_unmatched_files: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}